server:
  port: 8080

binlist:
  api:
    # in milliseconds
    # default value: 86400000 ms = 1 day
    clearBinCacheInterval: 86400000
    lookup:
      url: https://lookup.binlist.net/

card-cost:
  defaultClearingCost: 10

spring:
  application:
    name: card-cost-service
  data:
    rest:
      base-path: /api

  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:card-cost-db;DB_CLOSE_DELAY=-1
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
#    hibernate:
#      ddl-auto: create-drop
    properties:
      hibernate:
#        format_sql: true
#        generate_statistics: true
#        jdbc:
#          batch_size: 10
    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
