server:
  port: 8080

card-cost:
  # in milliseconds
  # default value: 86400000 ms = 1 day
  clearBinResponseCacheInterval: 86400000

spring:
  application:
    name: card-cost-service
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:card-cost-db;DB_CLOSE_DELAY=-1
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        format_sql: true
#        generate_statistics: true
        jdbc:
          batch_size: 10
    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true