# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Master Branch

on:
  push:
    branches:
      - 'master'

jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Build
        run: mvn -U clean install -B -Dmaven.test.skip -DskipITs
      - name: Unit Tests
        run: mvn -B -DskipITs test
      - name: Integration Tests
        run: mvn test-compile failsafe:integration-test
      - name: Static Code Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
